<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="../../src/Docker/Docker.csproj" />
		<ProjectReference Include="../../src/Azurite/Azurite.csproj" />
		<ProjectReference Include="../../src/MsSql/MsSql.csproj" />
		<ProjectReference Include="../../src/MySql/MySql.csproj" />
		<ProjectReference Include="../../src/Nats/Nats.csproj" />
		<ProjectReference Include="../../src/PostgreSql/PostgreSql.csproj" />
		<ProjectReference Include="../../src/RabbitMq/RabbitMq.csproj" />
		<ProjectReference Include="../../src/Redis/Redis.csproj" />
	</ItemGroup>
</Project>
